config/routes.rb
Rails.application.routes.draw do
  resources "entries"

  root 'welcome#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @websites = [
      ["http://railsgirls.com", "Rails Girls"],
      ["https://en.wikibooks.org/wiki/Ruby_Programming", "Wikibooks"],
      ["http://guides.rubyonrails.org", "Ruby on Rails Guides"],
    ]
    @name = "Agata"
    @entries = Entry.all

  end

  def show
    @entry= Entry.find(params["id"])
  end

  def new
  end

  def create
  entry_params = params["entry"].permit("title", "contents")
  entry = Entry.create(entry_params)
  redirect_to(entry_path(entry))
  end

  def edit
    @entry = Entry.find(params["id"])
  end

  def update
  entry_params = params["entry"].permit("title", "contents")
  entry = Entry.find(params["id"])
  entry.update(entry_params)
  redirect_to(entry_path(entry))
end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @websites = [
      ["http://railsgirls.com", "Rails Girls"],
      ["https://en.wikibooks.org/wiki/Ruby_Programming", "Wikibooks"],
      ["http://guides.rubyonrails.org", "Ruby on Rails Guides"],
    ]
    @name = "Agata"
    @entries = Entry.all

  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entries/edit.html.erb
<%= form_for(@entry) do |form| %>
  <p><%= form.label("title") %></p>
  <p><%= form.text_field("title") %></p>
  <p><%= form.label("contents") %></p>
  <p><%= form.text_area("contents") %></p>
  <p><%= form.submit %></p>
<% end %>
<p><%= link_to("Back to this entry", entry_path(@entry)) %></p>
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/entries/index.html.erb
<h1>My Rails Girls Diary</h1>
  <div>
    <% for entry in @entries %>
  <h2> <%=entry.title %></h2>
  <p><%=entry.date %></p>
  <p><%=entry.contents %> </p>

  <% end %>

  <% @entries.each do |entry| %>
  <h2><%= link_to(entry.title, entry_path(entry)) %></h2>
<%= link_to("New entry", new_entry_path) %>




  <% end %>

    <h2>My name is</h2>
      <p>20.05.2017</p>
      <p>Mam na imie <%@name%></p>


    <h2>Submitted a Rails Girls application</h2>
      <p>1.02.2014</p>
      <p>Just submitted an application to a Rails Girls workshop. Can’t wait to see whether I’ll get in!</p>
      <h2>Got in!</h2>
      <p>15.02.2014</p>
      <p>Received an email that my application got accepted! I’ll be at a RG workshop next week!</p>
    <h2>The first day starts…</h2>
      <p>22.02.2014</p>
      <p>Today is the first day of the Rails Girls workshop. My coach is quite strange but it seems we all have Rails installed now and can start learning.</p>
  </div>
  <div>
  <h1>My favourite websites</h1>
    <ul>
      <% for url, name in @websites %>
  <li><a href="<%= url %>"><%= name %></a></li>
<% end %>
    </ul>
  </div>
  <img src="http://railsgirls.com/images/rg-warsaw.png" />

app/views/entries/new.html.erb
<%= form_for(Entry.new) do |form| %>
  <p><%= form.label("title") %></p>
  <p><%= form.text_field("title") %></p>
  <p><%= form.label("contents") %></p>
  <p><%= form.text_area("contents") %></p>
  <p><%= form.submit %></p>
<% end %>
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/entries/show.html.erb
<h2> <%=@entry.title %></h2>
<p><%=@entry.date %></p>
<p><%=@entry.contents %> </p>

<p><%= link_to("Back to all entries", entries_path) %></p>

<p><%= link_to("Edit this entry", edit_entry_path(@entry)) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag "https://rawgithub.com/krzysztofbialek/Rails-Girls-Warsaw-App/master/style.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>My Rails Girls Diary</h1>
  <div>
    <% for entry in @entries %>
  <h2> <%=entry.title %></h2>
  <p><%=entry.date %></p>
  <p><%=entry.contents %> </p>

  <% end %>

  <% @entries.each do |entry| %>
  <h2> <%=entry.title %></h2>
  <p><%=entry.date %></p>
  <p><%=entry.contents %> </p>

  <% end %>

    <h2>My name is</h2>
      <p>20.05.2017</p>
      <p>Mam na imie <%@name%></p>


    <h2>Submitted a Rails Girls application</h2>
      <p>1.02.2014</p>
      <p>Just submitted an application to a Rails Girls workshop. Can’t wait to see whether I’ll get in!</p>
      <h2>Got in!</h2>
      <p>15.02.2014</p>
      <p>Received an email that my application got accepted! I’ll be at a RG workshop next week!</p>
    <h2>The first day starts…</h2>
      <p>22.02.2014</p>
      <p>Today is the first day of the Rails Girls workshop. My coach is quite strange but it seems we all have Rails installed now and can start learning.</p>
  </div>
  <div>
  <h1>My favourite websites</h1>
    <ul>
      <% for url, name in @websites %>
  <li><a href="<%= url %>"><%= name %></a></li>
<% end %>
    </ul>
  </div>
  <img src="http://railsgirls.com/images/rg-warsaw.png" />